version: "3.8"
services:
  postgres:
    container_name: unipile_connector_postgres
    image: postgres:16-alpine
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB_NAME}
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 3s
      timeout: 3s
      retries: 5
    networks:
      - backend
  redis:
    container_name: unipile_connector_redis
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT}:6379"
    env_file:
      - .env
    environment:
      - REDIS_REPLICATION_MODE='master'
      - ALLOW_EMPTY_PASSWORD='yes'
    volumes:
      - "./volumes/redis_data:/data"
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 3s
      timeout: 3s
      retries: 5
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "10"
    networks:
      - backend

networks:
  backend:
    driver: bridge
